[package]
name = "blockchain-in-rust"
version = "0.1.0"
authors = ["techHiveMinds"]
edition = "2018"
# readme = "README.md"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4"
crypto-hash = "0.3.4"
